USE planner;
ALTER TABLE plan ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE SET NULL;
ALTER TABLE comment ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE SET NULL;
ALTER TABLE comment ADD CONSTRAINT fk_user FOREIGN KEY (plan_id) REFERENCES plan(id) ON DELETE CASCADE;
